# Dockerfile.dev

FROM tensorflow/tensorflow:2.15.0-gpu

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Instala Jupyter y herramientas útiles de desarrollo
RUN pip install jupyter matplotlib seaborn ipykernel

COPY . .

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--NotebookApp.token="]
